In [4]:
import numpy as np

arr1 = np.array([1,2,3,4,5])  #1D array
arr2 = np.array([[1,2,3],[4,5,6]])  #2D array
arr3 = np.array([[0,1,2],[4,5,6],[7,8,9]])  #3D array
print(("1-D: ",arr1))
print(("2-D: ",arr2))
print(("3-D: ",arr3))

('1-D: ', array([1, 2, 3, 4, 5]))
('2-D: ', array([[1, 2, 3],
       [4, 5, 6]]))
('3-D: ', array([[0, 1, 2],
       [4, 5, 6],
       [7, 8, 9]]))


In [10]:
#array of zeroes
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
#array of 1s
ones = np.ones((4,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
#create an array with the gap of 2
range = np.arange(0, 10, 2)
print(range)

[0 2 4 6 8]


In [22]:
#create an array with random values
random = np.random.rand(3,3)
print(random)

[[0.68308315 0.39193134 0.57372603]
 [0.75664909 0.08256411 0.98335661]
 [0.26555693 0.27512507 0.50995827]]


In [24]:
arr1
for i in arr1:
    print(i)

1
2
3
4
5


In [36]:
#element wise addition
arr = np.array([1,2,3,4,5])
print(arr+2)
print(arr*2)
print(arr-1)
print(arr/2)
print(np.sqrt(arr))   #squareroot of each element
print(np.exp(arr))    #exponent
print(np.log(arr))    #log

[3 4 5 6 7]
[ 2  4  6  8 10]
[0 1 2 3 4]
[0.5 1.  1.5 2.  2.5]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [44]:
#array indexing and slicing - indexing
print(arr[0])
print(arr[1])
print(arr[4])
print(arr[-1])

1
2
5
5


In [49]:
#array indexing and slicing - slicing
print(arr[1:4])    #elements between index 1 -4
print(arr[:3])     #first 3 elements
print(arr[2:])     #last from index 2 to end
print(arr[1:4:2])  #elements between index 1 -4 with gap of 2

[2 3 4]
[1 2 3]
[3 4 5]
[2 4]


In [56]:
#boolean indexing
print(arr[arr>3])
#fancy indexing
indices = [0,1,3]
print(arr[indices])

[4 5]
[1 2 4]


In [60]:
#reshaping the array
arr = np.array([[1,2,3],[4,5,6]])
reshaped = arr.reshape((6,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [62]:
#transposing the array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
transposed = arr.T
print(transposed)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [69]:
#Aggregation Function
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(arr))  #sum of all elements
print(np.sum(arr,axis = 0))  #sum along columns
print(np.sum(arr,axis = 1))  #sum along rows
print(np.mean(arr))  #mean of all elements
print(np.min(arr))   #min in all elements
print(np.max(arr))   #max in all elements
print(np.argmax(arr))   #max value index
print(np.argmin(arr))   #min value index


45
[12 15 18]
[ 6 15 24]
5.0
1
9
8
0
